
"""
/***************************************************************************
 CAMSDataManager
                                 A QGIS plugin
 Manage and analyze CAMS air quality data in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-02
        copyright            : (C) 2025 by POLIMI
        email                : zhanbin.wu@mail.polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CAMSDataManager class from file CAMSDataManager.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cams_data_manager import CAMSDataManager
    return CAMSDataManager(iface)



